# Generated by Django 3.0 on 2019-12-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ratelweb.User')),
                ('b1', models.IntegerField(max_length=20, null=True)),
                ('b2', models.IntegerField(max_length=20, null=True)),
                ('b3', models.IntegerField(max_length=20, null=True)),
            ],
        ),
    ]
