# Generated by Django 3.0 on 2019-12-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='b1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='b2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='b3',
            field=models.IntegerField(null=True),
        ),
    ]
