# Generated by Django 2.2.1 on 2019-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelweb', '0002_auto_20191207_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark',
            field=models.CharField(default='1234567891011', max_length=13),
        ),
    ]
