# Generated by Django 3.0 on 2019-12-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelweb', '0002_auto_20191206_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='department',
            field=models.CharField(default='computer science', max_length=100),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(default='홍길동', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
