# Generated by Django 2.2.1 on 2019-12-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelweb', '0003_auto_20191211_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
