# Generated by Django 3.0 on 2019-12-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelweb', '0003_auto_20191206_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='aaa@gmail.com', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='b1',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='b2',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='b3',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='department',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='name',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark',
            field=models.IntegerField(default=1234567891011),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='iden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratelweb.User'),
        ),
    ]
