# Generated by Django 2.2.7 on 2019-12-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelweb', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark',
            field=models.CharField(default='1234567891011', max_length=130),
        ),
    ]
